### ISSUE TITLE
Feedback from constant reinstall issue

### ISSUE THREAD

**Issue by lyndhurst** [SidOfc/mkdx#121] opened 2020-08-31 19:45 UTC
Hi,
I am opening a new issue, because I cannot re-open the issue #114 , I guess it is too old.

I finally got time to spend almost a day tinkering with your plugin, and everything works fine. I had a few observations I wanted to share with you since you encouraged me to give some feedback if any. I am still on a KDE Neon 5.19 system using vim 8.1 by the way.

1. Regarding the constant *re-install* issue using `PlugUpdate`, I found out that it is still happening right after installation until I completely exit vim and start it again. Do not know if it is on me again, I thought it might be interesting to you.
2. In the README [mapping](https://github.com/SidOfc/mkdx#mappings) section, I noticed a typo while copy pasting some function names. From *italicize* to *strikethrough*, functions are refered to with a redundant `mkdx` e.g. `<Plug>(mkdx-mkdx-text-italic-{n|v})`. I assume they are redundant since removing them got my re-mapping working :smile: 

So nothing critical, I finally got a cleaner working config for your plugin; and it was a breeze this time around! 

I had one question regarding the highlighting though. I manage to customize a couple of items, but I cannot find which keyword is the `quoteBlockText` using. I get highlighting for the quote block delimiter symbols `>`  but not the actual text content. I will keep looking, but if you know, it might save me some time.

Thanks again for your patience last time.

**Comment by SidOfc** [comment] 2020-08-31 20:19
Hey @lyndhurst welcome back and thanks so much for opening a new issue!

I understand 1. better now, I've actually set up a command `vip` (Vim Install Plugin for short) which runs a `nvim +PlugInstall +qall` command from the terminal which exits vim afterwards, so I never stay inside vim, I'll give it a shot installing more than once while staying inside vim.

Also, I've found which mappings were wrong and fixed them, cheers for pointing that out!

**Comment by SidOfc** [comment] 2020-08-31 21:03
Oke so after some quick trial I was still unable to reproduce in either vim or nvim.
I checked by running `rm -rf ~/.vim/plugged/mkdx` so that the plugin would not be installed, then opening either `vim` or `nvim` and running `:PlugInstall` followed by two or more `:PlugInstall` and `:PlugUpdate` commands, for me, the result after initial install is always "Already installed" or "Already up to date", it does not clone the plugin twice. At least it is not harmful to reinstall mkdx although it is a bit annoying, I'll leave this issue open for a bit to see if I can reproduce with a VM. Actually, I'm not sure if it's possible for you to create / share a virtual box disk image I can install which shows the issue?

As for the syntax highlighting, mkdx itself does not actually do anything about the quote marks as far as I can tell (or see in the syntax file). When I check the syntax highlighting group I see that the `>` marker has a group of [`markdownBlockquote`](https://github.com/tpope/vim-markdown/blob/master/syntax/markdown.vim#L71) and the actual text inside the quote has no highlighting group, perhaps another plugin adds that highlighting group? I tried to do a [github search](https://github.com/search?q=quoteBlockText&type=Code) but it turned up empty for me.

If you want to check the highlighting group under the cursor, you can use a mapping like this:

```viml
  nmap <silent> <space>gp :echo map(
      \ synstack(line('.'), col('.')),
      \ 'synIDattr(v:val, "name")'
      \ )<Cr>
```

This maps <kbd>space</kbd><kbd>g</kbd><kbd>p</kbd> to display all highlighting groups of the character under the cursor.

If I place the cursor on a quote mark, I see the default vim markdown highlighting group for quote symbols:
![image](https://user-images.githubusercontent.com/3225058/91766453-e6744980-ebda-11ea-97fb-5140387f3281.png)

Now if I move to the text and use the same mapping, there is no highlight group there:
![image](https://user-images.githubusercontent.com/3225058/91766523-fb50dd00-ebda-11ea-8f3b-2ec0dfa777c7.png)

I don't think the default vim markdown plugin actually highlights text inside the quote different from other text.
Sorry for the somewhat lengthy reply there, I appreciate the effort in you coming back to me :+1: 

Like I said, I'll keep the issue open for a bit to dive deeper, let me know if you can share a disk image I can run!

**Comment by lyndhurst** [comment] 2020-09-01 08:17
Thanks for all the info, and this mapping tip about the highlighting group under cursor, that is really going to be helpful.

It is true the markdown plugin I was using before had a special highlighting group, but seeing the 'toggle block quote' gif in the README, I was under the impression your theme was highlighting the content, I realize now it must be the visual selection highlight... Like the rest I was pointing out, this is not critical, but you sure saved me some headache!

Getting back to the reinstall issue, I am sorry I did not snapshot the VM at the time I was figuring that out, that would have made it easier. I am going to isolate some steps to reproduce the issue, and provide you with an image if successful, but like the last time it might take me a few days at least, I am afraid.

I will not forget though, it is in my todo list! Thanks again for all the tips, it is greatly appreciated.

**Comment by SidOfc** [comment] 2020-09-11 12:44
Hello again @lyndhurst,

Just tested a KDE Neon 5.19.5 install in virtualbox, installed vim-plug and mkdx and unfortunately I still can't reproduce the issue you are describing. I'm not sure what exactly is wrong but it will be hard for me to figure out without being able to reproduce the issue :sweat_smile: 

That being said this is still the first time I'm hearing about this and it seems odd that a plugin manager always wants to reinstall mkdx even though it's already installed. Seeing as I can't reproduce on the same system as you're on I'm going to close this issue. If you get a VM showing the issue please do let me know in a comment since I could be wrong of course.

In any case cheers for the useful feedback up to this point, much appreciated :+1:

**Closed by SidOfc** 2020-09-11 12:44 UTC
Labels: bug:report
