### ISSUE TITLE
"o" insert newline deletes current line, on indented '# statement'

### ISSUE THREAD

**Issue by wiwo192** [SidOfc/mkdx#172] opened 2022-06-13 23:17 UTC
Hello there, thanks for reporting an issue or requesting a feature!
If you want to add a feature, you won't need this template. Just provide a clear
description of what you want and include an example of how this works in practice.

If you're opening a bug report,this template will help you fill out all the needed information,
simply replace the [TEMPLATE] data with actual information, fill out the checkboxes and include any
information you find useful and you're good to go!
When you're done, don't forget to re-read and remove dummy texts like this paragraph.

**OS type**:

- [ ] Unix
- [X] Mac
- [ ] Windows
- [ ] Other ([SPECIFY])

**Vim**:

- [X] vim
- [ ] neovim
- [ ] Other ([SPECIFY])

**Vim version**:

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 24 2021 14:13:29)
macOS version - arm64
Included patches: 1-3455
Compiled by GitHub Actions

**Reproduce steps**:

Example:

1. Open a markdown file.
2. Paste the following example into the file:
    # Indented line, with pound prefix    
3. Then, attempt to do [ACTION] in [MODE].
In normal mode, on that line, hit "o"

**Expected**:

Same behavior in vim. Insert new line, and go into insert mode in the newline

**Actual**:

The indented line got deleted, and go into insert mode of the same line.
![Kapture 2022-06-13 at 16 09 49](https://user-images.githubusercontent.com/1035133/173462754-f1bf2246-51e5-4061-96be-60b4cac7e6e6.gif)

**Comment by SidOfc** [comment] 2022-06-14 08:57
Hello @wiwo192,

I'm having trouble understanding the issue due to the bare description. Can you please clean it up a bit? Remove the issue template text at least and please provide a more detailed description of the problem you are facing.

**Comment by SidOfc** [comment] 2022-06-14 09:16
To be more specific:

- Does it happen when mkdx is the only plugin you have enabled?
- Which mkdx settings did you enable? (`g:mkdx#settings`)

If I understand correctly in your case a header disappears when pressing "o". I was unable to reproduce this myself, but I'm not entirely sure if that's all there is to it 😅

**Comment by SidOfc** [comment] 2022-06-14 09:32
Hello @wiwo192,

Cheers for reporting an issue, I have two more questions:

- Does it happen when mkdx is the only plugin you have enabled?
- Which mkdx settings did you enable? (`g:mkdx#settings`)

If I understand correctly in your case a header disappears when pressing "o". I was unable to reproduce this myself, but I'm not entirely sure if that's all there is to it 😅

**Comment by SidOfc** [comment] 2022-06-18 18:41
Since this issue hasn't received any activity I'm going to close it. Feel free to comment once you find the time.

**Closed by SidOfc** 2022-06-18 18:41 UTC
