### ISSUE TITLE
Unexpected behavior of period key in markdown documents

### ISSUE THREAD

**Issue by dzackgarza** [SidOfc/mkdx#95] opened 2020-03-16 03:52 UTC
Outside of markdown documents, the period key takes on the usual behavior (repeating the last action), but something in the plugin seems to override this behavior in markdown documents.

Something like `3>>.' normally indents 3 lines twice, but this doesn't seem to happen in markdown documents with this plugin installed -- it seems to paste text sometimes, delete characters at other times, or do nothing entirely, so it's not clear to me what the intended behavior actually is. In any case, is there any way to disable it?

**Comment by samarulmeu** [comment] 2020-03-16 08:59
I do not think that the problem resides in this plugin. I tried to reproduce your issue (`3>>`) opening  a markdown document with only this plugin enabled and it worked perfectly. Then I started to enable other markdown plugins that I used in the past and, after enabling *bullets.vim*, I got a strange behavior -- `.` did nothing. 

So maybe you have some other plugin that interferes with the mapping.

**Comment by SidOfc** [comment] 2020-03-16 10:46
@dzackgarza hello! Can you please tell me if you can reproduce this with _only_ mkdx enabled?
If indeed the "weird" behavior disappears as in @samarulmeu's case, then indeed it is likely something with your mappings / other plugins.

After doing this, if the issue persists, feel free to post a list of your plugins, and if possible / willing, your vimrc configuration, from there I can also get a lot of info.

Note that this is only needed if I think the issue resides within _mkdx_ itself. lets keep the discussion open for now, thanks for reporting and let me know when you find out more.

**P.S.** The provided issue template is not something to be "discarded" and just start typing, it is a means for me to see some basic info about your setup, please fill it in where possible next time.

Thanks for the feedback so far :+1:

**Comment by SidOfc** [comment] 2020-03-18 19:45
@dzackgarza hello!

Just wanted to ask, any more news on this?

**Comment by SidOfc** [comment] 2020-03-23 18:52
Since it's been over a week without a response, I'll close this issue if it remains inactive for another week.

**Comment by dzackgarza** [comment] 2020-03-28 03:14
Seems to have been a plugin conflict! No clue which it was though, sorry.

**Comment by SidOfc** [comment] 2020-03-29 10:23
Hello again @dzackgarza!

No problem! I noticed you had your dotfiles up on github so I decided to grab your [vimrc](https://github.com/dzackgarza/dotfiles/blob/master/vim/vimrc.symlink) and test it :)
Unfortunately though, I could not reproduce the issue, When I, for example, go to a list like:

```markdown
- item 1
- item 2
- item 3
```

And perform `3>>.` it actually does the correct thing for me. I must add that I made **one change** to your vimrc which was commenting out `set shell=/bin/zsh` because I don't use zsh, so it looks like this:

```viml
" set shell=/bin/zsh
```

I am not sure if this is the cause of the issue though but it might be worth checking it out for yourself if it doesn't break more important functionality. I'll close this issue now since I can't reproduce this and running with mkdx alone does not cause this behavior. I'm guessing some old configuration could be "in the way" which I do not have on my machine. 

P.S. (off-topic):
While checking your vimrc, I found you have multiple `let g:polyglot_disabled = [...]` statements in your vimrc, one for `latex`, another for `javascript` and `html`, and the one for mkdx to disable `markdown`. I think your intention here is to disable all four of those languages?

If that is indeed the case, there should only be one `let g:polyglot_disabled` declaration which includes everything you want to disable, like this:

```viml
let g:polyglot_disabled = ['latex', 'javascript', 'html', 'markdown']
```

Currently, you are overwriting it every time and only the last declaration `let g:polyglot_disabled = ['markdown']` will be applied :)

Thank you for reporting a potential defect nonetheless, it is always appreciated :+1:

**Closed by SidOfc** 2020-03-29 10:23 UTC
