### ISSUE TITLE
mkdx TOC does not support utf8 title

### ISSUE THREAD

**Issue by Cyperwu** [SidOfc/mkdx#130] opened 2020-09-25 11:17 UTC
**OS type**:

- [x ] Unix
- [ ] Windows
- [ ] Other ([SPECIFY])

**Vim**:

- [ ] vim
- [x ] neovim
- [ ] Other ([SPECIFY])

**Vim version**:

NVIM v0.5.0-nightly

**Reproduce steps**:

1. Open a markdown file.
2. Paste the following example into the file:
```
## 测试
```
3. Then, attempt to generate TOC

**Expected**:

```
# Table of Contents

- [Table of Contents](#table-of-contents)
  - [测试](#测试)

## 测试
```

**Actual**:

outputs:
```
# Table of Contents

- [Table of Contents](#table-of-contents)
  - [测试](#)

## 测试
```

**Comment by SidOfc** [comment] 2020-09-25 11:26
Yep that looks like a bug indeed, will check it out somewhere this week.

Cheers for the report :+1:

**Comment by Cyperwu** [comment] 2020-09-25 11:32
Thanks! And there is another bug that
```
## 1. test
```
generates
```
[1. xxx](#1-xxx)
```
The period was missing. Should I open a new issue or leave it here?

**Comment by SidOfc** [comment] 2020-09-25 15:20
@Cyperwu so it actually generated `[1 test](#1-test)` instead of `[1. test](#1-test)`?

**Comment by SidOfc** [comment] 2020-09-25 16:05
Oke so the issue with chinese characters should now be fixed (https://stackoverflow.com/questions/41318003/how-to-match-chinese-characters-with-grep) by including the unicode range of chinese.

About this other bug, I checked to see what gets generated when using `# 1. some heading` and I can't find any errors in the link text or actual link, it ends up like this: `[1. some heading](#1-some-heading)` which is correct in both text and generated fragment link on GH.

**Comment by Cyperwu** [comment] 2020-09-27 02:42
Sorry, I checked my code and found that it was related to my markdown preview tool. So that the related bug was actually not exist. Thanks!

**Comment by SidOfc** [comment] 2020-09-27 21:02
I can't reproduce this on either neovim (0.5.0) or regular vim (8.1), even after `set re=1` it works, I did however find some useful information when going to `:h E945` which shows me how to "fix" it. I've pushed the commit to master so you can try it out by updating.

I also patched another bug in there with YAML frontmatter showing up in generated table of contents because in markdown `---` is used for titles as well as YAML front matter.

**Comment by Cyperwu** [comment] 2020-09-28 06:26
It still raises `E945`, but the TOC is generated. 

I found some [code](https://github.com/mzlogin/vim-markdown-toc/blob/2e86c7229dfee5b7062194ec3d08a79a6b07de02/ftplugin/markdown.vim#L159) on [vim-markdown-toc](https://github.com/mzlogin/vim-markdown-toc). They support Chinese, Korean specifically but I think that's not the common use case for markdown writing.

**Comment by SidOfc** [comment] 2020-09-28 08:44
Hmmn very strange, also not very easy to fix for me as I don't get this error at all :(

What I think I'll try to do is split this one big range up into multiple smaller ones that are no more than 256 chars apart since that is the limit of the old regex engine. Unfortunately though I'll also have to ask for your feedback on it once I've committed some change since I can't reproduce it myself :sweat_smile: 

I'll keep you posted when I've worked more on it, will try to apply another patch after work.

**Comment by SidOfc** [comment] 2020-09-28 15:55
alright @Cyperwu can you update again and give it another shot?

The ranges are now split and should all be < 256 characters apart as per Vim limit. The only thing I can imagine that would cause it to fail is because they are all still in the same character class, but not as one giant range but quite a few small ranges. 

Cheers for your patience and feedback so far, looking forward to more info :+1:

**Comment by Cyperwu** [comment] 2020-09-29 07:54
Cheers, your patch works!

**Comment by SidOfc** [comment] 2020-09-29 08:34
Good stuff, will close this, thanks for reporting!

**Closed by SidOfc** 2020-09-29 08:34 UTC
Labels: bug:report
