### ISSUE TITLE
new list item with <enter>

### ISSUE THREAD

**Issue by kraxli** [SidOfc/mkdx#132] opened 2020-11-02 20:21 UTC
When I am at the end of the line of a list item and I press `enter` the new list item is created on the same line. For example:

```markdown
- item 1<enter>
```
results in

```markdown
- item 1-
```
instead of

```markdown
- item 1
- 
```
In case there is an empty space at the end of the line it works as expected.

Is this intentional?

My environment:
OS: Linux Mint 20 Ulyana
Vim: NVIM v0.4.4

Thanks
David

**Comment by SidOfc** [comment] 2020-11-03 21:50
Hi @kraxli,

This is definitely not intended behavior, did you also test mkdx in isolation? If not, could you try it without any other plugins enabled or otherwise if you did, share your vimrc so that I can reproduce?

Cheers for the feedback :+1:

**Comment by SidOfc** [comment] 2020-11-08 12:30
Hello again @kraxli, just wanted to ask, are you still facing the issue?
I'll close this issue in two days if left without a reply.

**Comment by SidOfc** [comment] 2020-11-10 23:13
Alright, closing this one for now. Feel free to comment here if anyone reading this is facing this issue!

**Closed by SidOfc** 2020-11-10 23:13 UTC
