### ISSUE TITLE
Checkbox  improvements 

### ISSUE THREAD

**Issue by paxtemper** [SidOfc/mkdx#2] opened 2017-12-22 05:55 UTC
It will be nice to have some checkbox highlighting for different state of it. Maybe default is to use colors from colorsheme, but have optional settings to set list of hexadecimal colors for each mark of checkbox.

Second i want command for toggle checkbox line, not only mark.

**Comment by SidOfc** [comment] 2017-12-22 13:57
Hi

Regarding your first request about checkbox highlighting, I'm not sure if this is something that fits the feature set that the plugin supplies. I will think about it, there is always an option to add it and have it off by default or to add a snipped that could be put directly in the .vimrc.

I'm not sure what you mean in your second request, could you elaborate?
Like do you want something that turns a regular list item into a checklist item for instance?

Cheers!

**Comment by paxtemper** [comment] 2017-12-22 17:55
I will explain second request in an example:
i want command to toggle between this two lines:
`do something bla bla bla`
to 
`[ ] do something bla bla bla`

Basically to toggle between normal line and checkbox list item.  And should pay attention that checkbox can be with some mark, [-], [x], or any other that user define. So, toggle  to normal non checkbox line independent from checkbox mark.  
And i expand my idea little bit more, to toggling line to be list item

`this is is text line`
to 
`- this is text line`

Maybe to both example be in one command, but i think is better to have two separated toggle commands.
I hope to my english is understandable.

**Comment by SidOfc** [comment] 2017-12-22 18:35
Thank you for the examples, they make it very clear what you want:

- Toggling between a regular line and a checkbox
- Toggling between a regular line and a list item

Currently, mappings like such already exist for toggling quotes (`>`) and heading levels, I don't think it will be difficult to add them to the existing set. To expand a bit on your idea, we could make them work in both normal and visual mode as well and optionally, have a third mapping which allows you to toggle between this: `this is a line` => `- [ ] this is a line` => `this is a line` as well.

The mappings could be like this:
- <kbd>PREFIX</kbd>+<kbd>li</kbd> = toggle between list/non-list item
- <kbd>PREFIX</kbd>+<kbd>c</kbd> = toggle between checkbox/non-checkbox item
- <kbd>PREFIX</kbd>+<kbd>cl</kbd> = toggle between checklist/non-checklist item

Thank you so far for your input, I will start working on this in the next few days.

**Comment by paxtemper** [comment] 2017-12-22 20:09
I have many ideas (some my, some  from other markdown plugins) to improve this plugin but i don't wan a make flood of features requests.
I know little bit of programming(mostly python), but nothing how make vim plugins, to try do something myself.

**Comment by SidOfc** [comment] 2017-12-23 02:09
That's good, I'm open to ideas, be it probably not every idea will "fit" the feature set that the plugin provides but simply put: If I think it fits the plugin and it would be a useful addition, why not? :)

If you want to get started with vimscript, I would highly suggest reading through [learn vimscript the hard way](learnvimscriptthehardway.stevelosh.com) by Steve Losh, you'll even create a small vim plugin yourself, also, vim helpfiles are your friend: `:h functions`. I believe vim plugins can be written in Python as well, or as a "native" neovim plugin even but I don't have any experience with that. Using vimscript has the advantage of working in every vim by default :)

**Comment by SidOfc** [comment] 2017-12-23 03:19
Hi @paxtemper,

If you want you can test the new functionality you requested in the branch `feature/toggling-improvements`.  Before I merge this into master, I will have to update documentation and create some GIFS which I will try to do soon.

For now, what you need to do is:

    $ cd ~/.vim/path/to/mkdx
    $ git pull origin feature/toggling-improvements
    $ git checkout feature/toggling-improvements

Should you at any time want to go back to master to update this plugin normally:

    $ cd ~/.vim/path/to/mkdx
    $ git checkout master

I've set up the mappings like this:

- <kbd>PREFIX</kbd>+<kbd>ll</kbd> = toggle between list/non-list item
- <kbd>PREFIX</kbd>+<kbd>t</kbd> = toggle between checkbox/non-checkbox item
- <kbd>PREFIX</kbd>+<kbd>lt</kbd> = toggle between checklist/non-checklist item

Commands work on the current line in normal mode, and on every selected line in visual mode.
Also, there is a global variable that allows you to set the default state of the checkbox: `g:mkdx#checkbox_initial_state = ' '` which defaults to a single space character.

**Comment by paxtemper** [comment] 2017-12-23 03:43
I try new features. New toggling commands work. But command for checking/marking checkbox are broken.

<kbd>PREFIX</kbd>+<kbd>-</kbd> give error:
`E118: Too many arguments for function: mkdx#ToggleCheckbox`


<kbd>PREFIX</kbd>+<kbd>=</kbd> have new checkbox/non-checkbox toggling effect.

I have this settings for marks, don't know does that is responsible for error

`let g:mkdx#checkbox_toggles = [' ', '-', 'o', 'x']
`

**Comment by SidOfc** [comment] 2017-12-23 03:56
Could you try again? I found the cause which was that I accidentally overwrote the original `mkdx#ToggleCheckbox` function which already existed -,- but it should be fixed now!

**Comment by paxtemper** [comment] 2017-12-23 04:21
Now work. But for me new functionalities are little bit confusing and none practical. Maybe i have different perception and needs.

First, for me checkbox line is list item in default. So i don't need to have `- [ ]`. That give some 'weird' toggling effects. For example:
`do this bla bla bla`
<kbd>prefix</kbd>+<kbd>lt</kbd>
`- [ ] do this bla bla bla`
<kbd>prefix</kbd>+<kbd>t</kbd>
result in this absurdity
`[ ] - [ ] do this bla bla bla`

I only need <kbd>prefix</kbd>+<kbd>t</kbd> and that work proper for me.  But all three toggling command combined need some better implementation.

**Comment by paxtemper** [comment] 2017-12-23 04:27
one more weird effects:

`list item`
<kbd>prefix</kbd>+<kbd>ll</kbd>
`- list item`
<kbd>enter</kbd> or <kbd>o</kbd>
`- -`

Why new item start with two - - ?

**Comment by SidOfc** [comment] 2017-12-23 04:37
Hmmn, I tried reproducing this issue in both vim and neovim and cannot reproduce this issue.
I've modified my `g:mkdx#checkbox_toggles` to match yours to check if that could be it but this was not the case. I've also checked this with a list item that was slightly indented to see if that caused the mismatch but that also came out negative. Do you have any other settings that you customized?

**Comment by paxtemper** [comment] 2017-12-23 04:51
When last time try new improvement i forgot to turn off my other markdown plugin. From now i will keep other markdown plugin down to avoid possible conflicts. I will test it and report.

**Comment by SidOfc** [comment] 2017-12-23 04:56
If this happens to conflict with another plugin, could you include the name of the plugin? Maybe it is something I can look into depending on what exactly the plugin does.

**Comment by paxtemper** [comment] 2017-12-23 04:58
- - error is gone when i turn other plugin, so it is plugin conflict. I link plugin to you know possible conflicts plugins:
https://github.com/plasticboy/vim-markdown

**Comment by SidOfc** [comment] 2017-12-23 20:38
Ah, cheers for linking the plugin, I checked it out and it does seem to do "something" within lists when pressing "o", mkdx provides both support for pressing the enter key at the end of a line, and pressing "o" in normal mode to insert new list items, however there is nothing that allows you to quickly indent/de-indent list items yet. It seems that PlasticBoy's vim-markdown provides some functionality for _indenting_ the list when pressing "o" followed by a special mark. I will look into this some more to see what more I can find, tonight I won't be home at least so it will probably be tomorrow or Monday.

**Comment by SidOfc** [comment] 2017-12-24 16:32
Changes are merged into master, I've added some instructions on unmapping functionality should it conflict in a way that makes the plugin unusable. You can revert back to master and pull the latest version @paxtemper :) Closing this issue.

**Closed** 2017-12-24 16:32 UTC
Labels: feature-request, question

**Comment by SidOfc** [comment] 2018-01-07 02:56
@paxtemper I've given the checkbox states a thought and added them as an opt-in feature.
It's in the branch [feature/checkbox-highlight-syntax](https://github.com/SidOfc/mkdx/tree/feature/checkbox-highlight-syntax), if you want, you can check it out locally :)

There are some things you need to know in case you want to try it out:

- It is not enabled by default, add this to your vimrc:
   `let g:mkdx#settings = { 'highlight': { 'enable': 1 } }` to enable the highlighting.
- The highlight groups are linked by default to some git groups, as can be seen [here](https://github.com/SidOfc/mkdx/blob/e920e0e278d5c5e23ae22b0177bb7d8fe8a7ab27/after/syntax/markdown/mkdx.vim#L9-L12)

To set a custom color for checkboxes, simply override the `mkdx*` group:

    hi link mkdxCheckboxEmpty Comment

Will cause empty checkboxes to be displayed as coment instead.
