### ISSUE TITLE
Conflict with Ultisnips plugin

### ISSUE THREAD

**Issue by samarulmeu** [SidOfc/mkdx#117] opened 2020-08-25 06:54 UTC
Hello!

Here I am with another bug report. When I try to use the VISUAL select option of Ultisnips (selecting a word and then pressing `tab` to have it inserted in a snippet) I get only a line indent, the word remaining unchanged. If I disable *mkdx* everything works as expected. 

Thank you for your time!

**Comment by SidOfc** [comment] 2020-08-25 09:15
Hey @samarulmeu!

Recently I added a feature which renumbers list items when pressing <kbd>tab</kbd> and <kbd>shift</kbd>+<kbd>tab</kbd>, this is likely what interferes. While I'm looking into the issue you can disable it by setting [g:mkdx#settings.tab.enable](https://github.com/SidOfc/mkdx#gmkdxsettingstabenable) to `0`:

```
let g:mkdx#settings = {
\ 'tab': {
\    'enable': 0
\ }
\ }
```

I'll check it out as soon as I can, cheers for the feedback :+1:

**Comment by samarulmeu** [comment] 2020-08-25 13:01
Thank you for the suggestion! After disabling the `tab` the snippets are working again.

**Comment by SidOfc** [comment] 2020-08-27 20:07
Hey @samarulmeu!

Just reporting back after doing some research, I am able to reproduce the issue and am looking into a solution using an `<expr>`  mapping. My idea here is to detect if we're in a numbered markdown list and if so, execute mkdx's handler, otherwise use whatever was mapped before. I'm not sure if I can actually make this work yet though.

In any case though if I can't, I do think I'll leave the feature on by default since most text processors offer this kind of functionality out of the box and I think it will be generally more used than expanding snippets in markdown documents.

Of course I could be wrong here so feel free to share some thoughts or suggestions if you've got them, cheers for reporting once again and I'll let you know when I find out more :+1:

**Comment by samarulmeu** [comment] 2020-08-29 22:34
Hey @SidOfc !

Sorry for the delayed reply. If it is too much trouble, I think you can let it on by default. But also will it be possible to just use the standard vim [bindings](https://vim.fandom.com/wiki/Shifting_blocks_visually) for indenting? Just a thought...

Cheers!

**Comment by SidOfc** [comment] 2020-08-30 12:07
You mean instead of using the tab key, you'd like to use `>>` and `<<` commands instead?
If that is the case I think the [remapping functionality](https://github.com/SidOfc/mkdx#remapping-functionality) section may be of help.

Since you probably have the feature disabled, all it really does is prevent them from being mapped so you could use this:

```viml

fun! s:MkdxRemap()
    nmap <buffer><silent> >> <Plug>(mkdx-indent)
    nmap <buffer><silent> << <Plug>(mkdx-unindent)
    vmap <buffer><silent> >> <Plug>(mkdx-indent)
    vmap <buffer><silent> << <Plug>(mkdx-unindent)
endfun
augroup Mkdx
    au!
    au FileType markdown,mkdx call s:MkdxRemap()
augroup END
```

If more folks come in with complaints about this I'll consider creating some special settings such as [`g:mkdx#settings.map.prefix`](https://github.com/SidOfc/mkdx#gmkdxsettingsmapprefix) to allow remapping this key without all the boilerplate.

Let me know if this works for you!

**Comment by samarulmeu** [comment] 2020-08-30 12:20
Thank you for the work around. For me was enough to just disable the indent as you’ve mentioned in a previous comment. Ultsnips is more important to me than list indenting (never miss it), but maybe is just my case.

Thank you for your time and help!

**Comment by SidOfc** [comment] 2020-08-30 13:04
No problem, and yeah list renumbering on indent is a bit subjective, it depends on how users use markdown files e.g. to keep track of progress or other generic list scenarios. In those cases it is definitely nice to renumber list items with tab/s-tab.

For now I'll close this issue then, as always thanks for the feedback!

**Closed by SidOfc** 2020-08-30 13:04 UTC
Labels: bug:report
